application:
  subdomain: airstation
  background_task: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://airstation:7331/
services:
  airstation:
    # docker.io/cheatsnake/airstation:1.0.0
    # upstream: docker.io/cheatsnake/airstation:1.4.1
    image: docker.1ms.run/cheatsnake/airstation:1.4.1
    environment:
      - AIRSTATION_SECRET_KEY={{ stable_secret "airstation_secret_key" }}
      - AIRSTATION_JWT_SIGN={{ stable_secret "airstation_jwt_sign" }}
    binds:
      - /lzcapp/var/storage:/app/storage/
      - /lzcapp/var/static:/app/static/
    healthcheck:
      test:
        - CMD
        - wget
        - --spider
        - -q
        - http://localhost:7331/
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
